on:
  pull_request:
    types: [closed]
    branches: 
      - dev
name: release-please
jobs:
  release-please:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true &&
         github.head_ref != 'release-please--branch--dev')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
          package-name: test
          default-branch: dev
          bump-minor-pre-major: true
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'