on:
  push:
    branches:
      - dev
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
          package-name: test
          default-branch: dev
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true