on:
  push:
    branches: 
      - dev
name: release-please
jobs:
  release-please-php-redis:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          command: manifest
          monorepo-tags: true
          default-branch: dev